backend:
  name: git-gateway
  branch: main

media_folder: "media_folder" # "site/static/img" # Folder where user uploaded files should go
public_folder: "public_folder" # "/img"

local_backend: true

collections:
[]
